version: '3.1'
services:
  app:
    container_name: app_todo
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    command: npm run start:dev
    volumes:
      - .:/app/
    depends_on:
      - db
  db:
    image: postgres:12.4-alpine
    container_name: db_todo
    ports:
      - 5432:5432
    env_file:
      - .env
